version: '3'

# networks:
#   proxy:
#     external: true
#   internal:
#     external: false

volumes:
  sonarr:
    driver: local
  radarr:
    driver: local

services:

  jackett:
    image: linuxserver/jackett:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
      ports:
        - 9117:9117
    # labels:
    #   - traefik.backend=jackett
    #   - traefik.frontend.rule=Host:jackett.josverheij.nl
    #   - traefik.docker.network=proxy
    #   - traefik.port=9117
    # networks:
    #   - internal
    #   - proxy
    volumes:
      - ${CONFIG_DIR}/jackett:/config

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    ports:
      - 8989:8989
    environment:
      TZ: "Europe/Amsterdam"
    #   PGID: 50
    #   PUID: 1000
    # labels:
    #   - traefik.backend=sonarr
    #   - traefik.frontend.rule=Host:sonarr.josverheij.nl
    #   - traefik.docker.network=proxy
    #   - traefik.port=8989
    # networks:
    #   - internal
    #   - proxy
    volumes:
      - sonarr:/config
      - ${DOWNLOAD_DIR}/complete:/downloads
      - ${VIDEO_DIR}/tv:/tv

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
    ports:
      - 7878:7878
    #   PGID: 50
    #   PUID: 1000
    # labels:
    #   - traefik.backend=radarr
    #   - traefik.frontend.rule=Host:radarr.josverheij.nl
    #   - traefik.docker.network=proxy
    #   - traefik.port=7878
    # networks:
    #   - internal
    #   - proxy
    volumes:
      - radarr:/config
      - ${DOWNLOAD_DIR}/complete:/downloads
      - ${VIDEO_DIR}/movies:/movies