version: '3'

# networks:
#   proxy:
#     external: true
#   internal:
#     external: false

volumes:
  sonarr:
    driver: local
  radarr:
    driver: local

services:
  # transmission:
  #   image: linuxserver/transmission:latest
  #   restart: always
  #   environment:
  #     TZ: "Europe/Amsterdam"
  #   ports:
  #     - 9091:9091
  #   networks:
  #     - internal
  #     - proxy
  #   volumes:
  #     - ${CONFIG_DIR}/transmission:/config
  #     - ${VIDEO_DIR}:/video

  jackett:
    image: linuxserver/jackett:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
    ports:
      - 9117:9117
    # networks:
    #   - internal
    #   - proxy
    volumes:
      - ${CONFIG_DIR}/jackett:/config

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    ports:
      - 8989:8989
    environment:
      TZ: "Europe/Amsterdam"
      PGID: ${PGID}
      PUID: ${PUID}
    # networks:
    #   - internal
    #   - proxy
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${VIDEO_DIR}:/video

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
      PGID: ${PGID}
      PUID: ${PUID}
    ports:
      - 7878:7878
    # networks:
    #   - internal
    #   - proxy
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${VIDEO_DIR}:/video