version: '3'

volumes:
  sonarr:
    driver: local
  radarr:
    driver: local

services:
  transmission:
    image: linuxserver/transmission:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
      PGID: ${PGID}
      PUID: ${PUID}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./transmission:/config
      - ${VIDEO_DIR}:/video
    logging:
      driver: none

  jackett:
    image: linuxserver/jackett:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
    ports:
      - 9117:9117
    volumes:
      - ${CONFIG_DIR}/jackett:/config
    logging:
      driver: none

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    ports:
      - 8989:8989
    environment:
      TZ: "Europe/Amsterdam"
      PGID: ${PGID}
      PUID: ${PUID}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${VIDEO_DIR}:/video
    logging:
      driver: none

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
      PGID: ${PGID}
      PUID: ${PUID}
    ports:
      - 7878:7878
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${VIDEO_DIR}:/video
    logging:
      driver: none