version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  traefik:
    image: traefik:alpine
    restart: always
    ports:
      - 18088:80
      - 18443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - ./rules:/rules
    # env_file:
    #   - traefik.env
    networks:
      - internal
      - proxy
