version: '3'

networks:
  proxy:
    external: true
services:
  traefik:
    image: traefik:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik.toml:/traefik.toml
      - ${PWD}/acme.json:/acme.json
    networks:
      - proxy