version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  traefik:
    image: traefik:alpine
    restart: always
    ports:
      - 8088:80
      - 8443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/acme.json:/acme.json
      - ${PWD}/rules:/rules
    # env_file:
    #   - traefik.env
    networks:
      - internal
      - proxy