version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:

  hass:
    image: homeassistant/home-assistant:latest
    restart: always
    environment:
      - TZ="Europe/Amsterdam"
    volumes:
      - ${HASS_CONFIG}:/config
    ports:
      - 8123:8123
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.backend=hass
      - traefik.frontend.rule=Host:josverheij.synology.me
      - traefik.docker.network=proxy
      - traefik.port=8123
    devices:
      - ${ZWAVE_DEVICE}:/dev/zwave:rwm