version: '3'

# networks:
#   proxy:
#     external: true
#   internal:
#     external: false

services:
  db:
    image: postgres:alpine
    restart: always
    # networks:
    #   - internal
    volumes:
      - dbhassvol:/var/lib/postgresql/data

  hass:
    image: homeassistant/home-assistant:latest
    restart: always
    environment:
      - TZ="Europe/Amsterdam"
    volumes:
      - ${HASS_CONFIG}:/config
    ports:
      - 8123:8123
    # networks:
    #   - internal
    #   - proxy
    # labels:
    #   - traefik.backend=hass
    #   - traefik.frontend.rule=Host:hass.josverheij.nl
    #   - traefik.docker.network=proxy
    #   - traefik.port=8123
    devices:
      - ${ZWAVE_DEVICE}:/dev/zwave:rwm
    depends_on:
      - db

volumes:
  dbhassvol:
    driver: local
