version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

volumes:
  sonarr:
    driver: local
  radarr:
    driver: local

services:
  transmission:
    image: linuxserver/transmission:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
    labels:
      - traefik.backend=transmission
      - traefik.frontend.rule=Host:transmission.josverheij.nl
      - traefik.docker.network=proxy
      - traefik.port=9091
    networks:
      - internal
      - proxy
    volumes:
      - ${PWD}/transmission:/config
      - /Volumes/SamsungS2/downloads:/downloads

  jackett:
    image: linuxserver/jackett:latest
    restart: always
    environment:
      TZ: "Europe/Amsterdam"
    labels:
      - traefik.backend=jackett
      - traefik.frontend.rule=Host:jackett.josverheij.nl
      - traefik.docker.network=proxy
      - traefik.port=9117
    networks:
      - internal
      - proxy
    volumes:
      - ${PWD}/jackett:/config

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    ports:
      - 8989:8989
    environment:
      TZ: "Europe/Amsterdam"
      PGID: 50
      PUID: 1000
    networks:
      - internal
      - proxy
    volumes:
      - sonarr:/config
      - /Volumes/SamsungS2/downloads/complete:/downloads
      - /Volumes/SamsungS2/tv:/tv

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    ports:
      - 7878:7878
    environment:
      TZ: "Europe/Amsterdam"
      PGID: '50'
      PUID: '1000'
    networks:
      - internal
      - proxy
    volumes:
      - radarr:/config
      - /Volumes/SamsungS2/downloads:/downloads
      - /Volumes/SamsungS2/movies:/movies