version: '3'

services:
  transmission:
    image: linuxserver/transmission:latest
    restart: always
    ports:
      - 9091:9091
    environment:
      TZ: "Europe/Amsterdam"
    networks:
      - media
    volumes:
      - ${PWD}/transmission:/config
      - /mnt/usb/downloads:/downloads

  jackett:
    image: linuxserver/jackett:latest
    restart: always
    ports:
      - 9117:9117
    environment:
      TZ: "Europe/Amsterdam"
    networks:
      - media
    volumes:
      - ${PWD}/jackett:/config

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    ports:
      - 8989:8989
    environment:
      TZ: "Europe/Amsterdam"
      PGID: 50
      PUID: 1000
    networks:
      - media
    volumes:
      - sonarr:/config
      - /mnt/usb/downloads/complete:/downloads
      - /mnt/usb/tv:/tv

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    ports:
      - 7878:7878
    environment:
      TZ: "Europe/Amsterdam"
      PGID: '50'
      PUID: '1000'
    networks:
      - media
    volumes:
      - radarr:/config
      - /mnt/usb/downloads:/downloads
      - /mnt/usb/movies:/movies

volumes:
  sonarr:
    driver: local
  radarr:
    driver: local

networks:
  media:
    driver: bridge